name: Tests

# Controls when the workflow will run
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install libGLU library on Ubuntu
      run: |
            if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install -y libglu1-mesa
            fi
      shell: bash
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: pytest test
